apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
  namespace: data-service
spec:
  type: NodePort
  ports:
  - port: 1935
    targetPort: 1935
    nodePort: 30008
  selector:
    name: nginx-rtmp-service