apiVersion: v1
kind: Service
metadata:
  name: common-redis
  namespace: data-service
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30007
  selector:
    name: common-redis