apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: data-service # 部署到的命名空间
  labels:
    name: consul
spec:
  type: NodePort
  ports:
    - name: http
      port: 8500
      nodePort: 30004
      targetPort: 8500
    - name: https
      port: 8443
      nodePort: 30005
      targetPort: 8443
  selector:
    app: consul