apiVersion: v1
kind: Service
metadata:
    name: tracker
    labels:
        app: tracker
    namespace: data-service
spec:
    selector:
        app: tracker # 这里选择器一定要选择容器的标签
    type: NodePort  # 此处可以是ClusterIP，但ClusterIP只能在集群内部调用，外网访问不了
    clusterIP: 10.96.0.110
    ports:
    - name: "22122"
      port: 22122
      targetPort: 22122
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
    name: storage0
    labels:
        app: storage0
    namespace: data-service
spec:
    selector:
        app: storage0
    type: NodePort
    ports:
    - name: "23000"
      port: 23000
      targetPort: 23000
      nodePort: 30003
